/**
 * 好长好大- -
 */
function dealWith()
        {
            var month;
            var day;
            month = document.getElementById("Month").value;
            day = document.getElementById("Day").value;
            if(month==1)
            {
                if(day>=1&&day<=20)
                {
                    document.getElementById("show").innerHTML="摩羯座Capricorn";
                }
                if(day>=21&&day<=31)
                {
                    document.getElementById("show").innerHTML="水瓶座Aquarius";
                }
            }
            if(month==2)
            {
                if(day>=1&&day<=19)
                {
                    document.getElementById("show").innerHTML="水瓶座Aquarius";
                }
                if(day>=20&&day<=29)
                {
                    document.getElementById("show").innerHTML="双鱼座Pisces";
                }
            }
            if(month==3)
            {
                if(day>=21&&day<=31)
                {
                    document.getElementById("show").innerHTML="白羊座Aries";
                }
            }
            if(month==4)
            {
                if(day>=1&&day<=20)
                {
                    document.getElementById("show").innerHTML="白羊座Aries";
                }
                if(day>=21&&day<=30)
                {
                    document.getElementById("show").innerHTML="金牛座Taurus";
                }
            }
            if(month==5)
            {
                if(day>=1&&day<=21)
                {
                    document.getElementById("show").innerHTML="金牛座Taurus";
                }
                if(day>=22&&day<=31)
                {
                    document.getElementById("show").innerHTML="双子座Gemini";
                }
            }
            if(month==6)
            {
                if(day>=1&&day<=21)
                {
                    document.getElementById("show").innerHTML="双子座Gemini";
                }
                if(day>=22&&day<=30)
                {
                    document.getElementById("show").innerHTML="巨蟹座Cancer";
                }
            }
            if(month==7)
            {
                if(day>=1&&day<=22)
                {
                    document.getElementById("show").innerHTML="巨蟹座Cancer";
                }
                if(day>=23&&day<=31)
                {
                    document.getElementById("show").innerHTML="狮子座Leo";
                }
            }
            if(month==8)
            {
                if(day>=1&&day<=22)
                {
                    document.getElementById("show").innerHTML="狮子座Leo";
                }
                if(day>=23&&day<=31)
                {
                    document.getElementById("show").innerHTML="处女座Virgo";
                }
            }
            if(month==9)
            {
                if(day>=1&&day<=23)
                {
                    document.getElementById("show").innerHTML="处女座Virgo";
                }
                if(day>=24&&day<=30)
                {
                    document.getElementById("show").innerHTML="天秤座Libra";
                }
            }
            if(month==10)
            {
                if(day>=1&&day<=23)
                {
                    document.getElementById("show").innerHTML="天秤座Libra";
                }
                if(day>=24&&day<=31)
                {
                    document.getElementById("show").innerHTML="天蝎座Scorpio";
                }
            }
            if(month==11)
            {
                if(day>=1&&day<=22)
                {
                    document.getElementById("show").innerHTML="天蝎座Scorpio";
                }
                if(day>=23&&day<=30)
                {
                    document.getElementById("show").innerHTML="射手座Sagittarius";
                }
            }
            if(month==12)
            {
                if(day>=1&&day<=21)
                {
                    document.getElementById("show").innerHTML="射手座Sagittarius";
                }
                if(day>=22&&day<=31)
                {
                    document.getElementById("show").innerHTML="摩羯座Capricorn";
                }
            }
        }